# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'STIMA3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import os
import sys
import networkx as nx
from Graph import*
from UCS import*
from Utils import*

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 351, 701))
        self.frame.setStyleSheet("background-color:rgb(36, 31, 49)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.open_file)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 311, 17))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(40, 300, 271, 23))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setAutoFillBackground(False)
        self.radioButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 340, 112, 23))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 540, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(350, 0, 931, 701))
        self.frame_2.setStyleSheet("background-color:rgb(61, 56, 70)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 81))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(30, 100, 871, 541))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.widget.setObjectName("widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Define the size of the widget
        widget_size = self.widget.size()

        # Create a Figure object
        self.figure = Figure(figsize=(widget_size.width(), widget_size.height()))

        # Add a canvas to the widget
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setParent(self.widget)
        
        # Set the fixed size for the widget
        self.widget.setFixedSize(widget_size)

        # Set the size of the Figure object
        self.figure.set_size_inches(widget_size.width()/100, widget_size.height()/100)

        # Create a Matplotlib figure and canvas, i want the figure to be the size of the widget
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setParent(self.widget)

        # Add a Graph figure to the matplotlib canvas
        self.graph = self.figure.add_subplot(111)
        self.graph.set_axis_off()


        # Create a push button to trigger the plot update
        self.plot_button = QtWidgets.QPushButton(self.frame)
        self.plot_button.setGeometry(QtCore.QRect(40, 400, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.plot_button.setFont(font)
        self.plot_button.setStyleSheet("color: rgb(255, 255, 255)")
        self.plot_button.setObjectName("plot_button")
        self.plot_button.clicked.connect(self.update_plot)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def open_file(self):
        file_dialog = QFileDialog()
        file_path, _ = file_dialog.getOpenFileName(None, "Open File", "", "Text Files (*.txt);;All Files (*.*)")
        if file_path:
            # Do something with the selected file, e.g. display its path in a label
            print("Selected file:", file_path)
            self.update_label(os.path.basename(file_path))

    def update_label(self, filename=None):
        if filename:
            self.label_3.setText(f"Filename: {filename}")
        else:
            self.label_3.setText("Filename")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Upload"))
        self.label_2.setText(_translate("MainWindow", "Choose File"))
        self.label_3.setText(_translate("MainWindow", "Filename:"))
        self.radioButton.setText(_translate("MainWindow", "Uniform Cost Search"))
        self.radioButton_2.setText(_translate("MainWindow", "A-Star"))
        self.pushButton_2.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Shortest Path Solver"))

    def update_plot(self):
        # Clear the previous plot
        self.graph.clear()

        # Add nodes and edges to the NetworkX graph
        G = nx.DiGraph()
        graph = Graph()
        graph.createGraph("test/map4.txt")
        # insert edges to G
        graph.printGraph()
        for node in graph.nodes:
            for neighbor in graph.nodes[node]:
                G.add_edge(node, neighbor, weight=graph.nodes[node][neighbor])
        start = 1
        goal = 14
        ucs = UCS(graph, start, goal)
        ucspair = list_to_adjacent_pairs(ucs.path)
        # ucspath = ucs(graph, start, goal)
        # ucspair = list_to_adjacent_pairs(ucs(graph, start, goal))
        print(f'Path : {ucs.path}')
        print(f'Cost : {ucs.cost}')
        # Draw the NetworkX graph on the Matplotlib figure
        pos = nx.circular_layout(G)
        # color blue for 1->3;  2->3
        edge_colors = ['red' if (u,v) in ucspair else 'black' for u,v in G.edges()]
        nx.draw_networkx_nodes(G, pos)
        nx.draw_networkx_labels(G, pos)
        nx.draw_networkx(G, pos, with_labels=True, font_weight='bold', node_color='red', alpha=0.7, node_size=2000, ax=self.graph, edge_color=edge_colors, width=[1 if c=='black' else 4 for c in edge_colors])

        # Update the canvas
        self.canvas.draw()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
